"""Neural implicit minimal-surface solver (paper Sec. 2.3, Eq. 3).

This is a from-scratch reimplementation of the core idea in DeepCurrents
(Palmer, Smirnov, Wang, Chern, Solomon 2021; ../DeepCurrents), which the
paper builds on directly (their ref. [22]): represent the surface implicitly
as the zero level set of a network f_theta(x), and drive del(f_theta)
towards -alpha_Gamma(x), the Biot-Savart-type vector field generated by the
polygonal boundary curve(s) Gamma, so that at convergence the "current"
del(f_theta)(x) + alpha_Gamma(x) vanishes and {f_theta = 0} is the
(approximately) area-minimizing surface spanning Gamma. We reuse the same
architecture and Biot-Savart formula as DeepCurrents' `deepcurrents.models`
but drop its pytorch3d dependency (unused by the minimal-surface path).
"""
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F

DOMAIN = (-1.0, 1.0)


def resample_closed_polyline(curve, n):
    """Resample a closed polyline (K,3) to exactly n points, evenly spaced
    by arc length."""
    curve = np.asarray(curve, dtype=float)
    closed = np.concatenate([curve, curve[:1]], axis=0)
    seg = np.linalg.norm(np.diff(closed, axis=0), axis=1)
    cum = np.concatenate([[0], np.cumsum(seg)])
    total = cum[-1]
    targets = np.linspace(0, total, n, endpoint=False)
    out = np.empty((n, 3))
    for i, t in enumerate(targets):
        j = np.searchsorted(cum, t, side='right') - 1
        j = np.clip(j, 0, len(seg) - 1)
        local = (t - cum[j]) / max(seg[j], 1e-12)
        out[i] = closed[j] + local * (closed[j + 1] - closed[j])
    return out


def biot_savart_3d(x, verts):
    """x: [B, m, 3] query points. verts: [B, L, n, 3] loops (L loops of n
    points each, shared across the batch or broadcastable). Returns [B, m, 3]
    the vector field alpha_Gamma at each query point."""
    x = x[:, None, :, None]                    # [B, 1, m, 1, 3]
    verts = verts[:, :, None]                  # [B, L, 1, n, 3]
    edges = torch.roll(verts, -1, dims=-2) - verts
    tangents = F.normalize(edges, p=2, dim=-1)
    disp = x - verts
    dir0 = F.normalize(disp, p=2, dim=-1)
    dir1 = torch.roll(dir0, -1, dims=-2)
    normals = torch.cross(
        tangents.expand(-1, -1, x.shape[2], -1, -1), disp, dim=-1)
    perpdist = normals.norm(p=2, dim=-1, keepdim=True)
    dot0 = (dir0 * tangents).sum(-1, keepdim=True)
    dot1 = (dir1 * tangents).sum(-1, keepdim=True)
    V = normals * (dot1 - dot0) / perpdist.pow(2).clamp(min=1e-10)
    return V.sum((1, 3)) / 1000


class InputMapping(nn.Module):
    """Random Fourier feature embedding (Tancik et al. 2020)."""

    def __init__(self, d_in, d_out, sigma=2):
        super().__init__()
        self.B = nn.Parameter(torch.randn(d_out // 2, d_in) * sigma,
                               requires_grad=False)

    def forward(self, x):
        x = (2 * np.pi * x) @ self.B.T
        return torch.cat([torch.sin(x), torch.cos(x)], dim=-1)


class SurfaceModel(nn.Module):
    """f_theta: R^3 -> R, plus the "current" del(f) + alpha_Gamma used for
    the minimal-surface loss (Eq. 3)."""

    def __init__(self, bdry, rff_sigma=2, hidden=256, rff_dim=2048):
        super().__init__()
        self.rff = InputMapping(3, rff_dim, sigma=rff_sigma)
        self.f = nn.Sequential(
            nn.Linear(rff_dim, hidden), nn.Softplus(),
            nn.Linear(hidden, hidden), nn.Softplus(),
            nn.Linear(hidden, hidden), nn.Softplus(),
            nn.Linear(hidden, hidden), nn.Softplus(),
            nn.Linear(hidden, 1),
        )
        self.register_buffer('bdry', bdry)  # [L, n, 3]

    def forward(self, x, only_f=False):
        x = x.clamp(*DOMAIN)
        y = self.rff(x)
        f = self.f(y)
        if only_f:
            return f
        df = torch.autograd.grad(
            outputs=f, inputs=x, grad_outputs=torch.ones_like(f),
            create_graph=True, only_inputs=True)[0]
        alpha = biot_savart_3d(x[None], self.bdry[None]).flatten(0, 1)
        current = df + alpha
        return {'f': f, 'current': current, 'df': df, 'alpha': alpha}
